### PR TITLE
Feature improvement 2.0

### PR DESCRIPTION
**Pull request by bstiq**
New shield for the elite-c that brings the improvements of the blackpill one.

#### PCBs
- [x] more visible détrompeur like on the Blackpill shield ( on hidden side once installed/opposite of rst button)
- [x] fancy fonts etc
- [x] new edge cuts for top screw, new fancy corners
- [x] matrix headers under elite c
- [x] make the wiring on both sides the same (currently, on blackpill shield is different)
- [x] move rst button
- [x] add pullups on serial for input devices on both sides
- [x] I2c connector
- [x] flip scl and sda in wiring (to keep compatibility with screens)

#### PCB - bonus
- [x] RAW connector for battery charge when using nice nanos

#### 3d models
- [x] remove elite c organic tents from the skeletyl repo, switch to only Blackpill tents as new elite c shield will be longer
- [x] update git description and folder structure

### Firmware
For @0xcharly 
- [x] create 2.0 firmware repo in scylla, tbk mini, skeletyl, charybdis
- [x] change pinout
- [x] add viaL everywhere
- [x] compile and save default hex files
- [ ] change serial pin to pin 5 (to accomodate for optional i2c)

### Others
- [x] Close charybdis shield git repo and link to new adapter

### Testing
- [x] test on Charybdis builds
- [ ] n!n compatibility
- [x] StemCell compatibility 

### Cancelled
- [x] add resistors for i2c
- [x] wire i2c
- [x] add resistor for handedness
- [x] think of system to allow use of pro micro (add option on pcb to reroute bottom pins)

### CODE REVIEW

**Comment by bstiq** [comment]
As mentioned by fauxpark, we can't use i2c between master and slave, as it is already used by the SPI devices (eg trackball).
I switched back to serial

**Comment by bstiq** [comment]
image

Current state of things 🥳

**Comment by bstiq** [comment]
Just double checked button is in the correct plate - 15mm (one hex hole) + 3mm (align skeletyl/CNano) - OK

**Comment by bstiq** [comment]
Edge cuts are not correct - modified them, need to reroute

**Comment by bstiq** [comment]
New edge cuts

image

**Comment by bstiq** [comment]
new i2c connector and on/off switch for nice nano

image

**Comment by bstiq** [comment]
Ordered PCBs, now waiting

**Comment by karrui** [comment]
Will an updated guide for this PCB and where to connect nicenano batteries be up on the documentation site soon?

**Comment by bstiq** [comment]
Hello,

I still have to finish, but here is the docs:
https://docs.bastardkb.com/hc/en-us/articles/4959519032466-Prepare-the-Elite-C-v2-

The part with installing the cables is missing but pretty straightforward.

I have no plans for nice!nano instructions at this point.
Regards,

**Comment by karrui** [comment]
Thanks. Can I have a little guidance on how to use the B+/B- battery pins for nice!nano then?

**Comment by bstiq** [comment]
Hey,

For this I recommend looking into n!n documentation, I'm not familiar with it.
It should work just like any other handwired or PCB keyboard.

Regards,

**Comment by karrui** [comment]
No worries, thanks for even designing for compatibility with n!n!

**Pull request merged**
